### ISSUE TITLE
Can't verify the params for openAddress function

### ISSUE THREAD

**Issue by emeryao** [Emeryao/WechatJSSDK.d.ts#3]
@neoblackcap Could you please show me the documents related to the `openAddress` function?
I just found some blogs about this API but not from the official Weixin document, so I'm not very confident about the `openAddress` function.
Thanks in advance.

**Comment by neoblackcap** [comment]
@Emeryao the official API documentation is [here](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=7_8&index=7), and if a user want to use this API, it must use the `http://res.wx.qq.com/open/js/jweixin-1.1.0.js` file instead of `http://res.wx.qq.com/open/js/jweixin-1.0.0.js`
PS: Wechat documentation is suck.

**Comment by emeryao** [comment]
Thanks @neoblackcap 
Tencent is also suck :laughing:
